name: smart_notes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4 # For image selection
  camera: ^0.10.5+2 # For camera access
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  image_cropper: ^5.0.1
  flutter_tesseract_ocr: ^0.4.24 # Add this line
  uuid: ^4.3.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true